language: csharp
solution: ExcelTableConverter.sln
install:
  - nuget restore ExcelTableConverter.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ExcelTableConverter.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ExcelTableConverter.ExcelContent.Tests/bin/Release/ExcelTableConverter.ExcelContent.Tests.dll
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ExcelTableConverter.JiraTableConverter.Tests/bin/Release/ExcelTableConverter.JiraTableConverter.Tests.dll
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ExcelTableConverter.LatexTableConverter.Tests/bin/Release/ExcelTableConverter.LatexTableConverter.Tests.dll
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./ExcelTableConverter.Utilities.Tests/bin/Release/ExcelTableConverter.Utilities.Tests.dll